backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "news"
    label: "الأخبار"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "الصورة", name: "thumbnail", widget: "image" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
